version: '3'
services:
  n8n:
    image: n8nio/n8n:1.113.3
    ports:
      - 5678:5678

    restart: always
    env_file:
      - .env
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_HOST=pg-n8n
      - DB_POSTGRESDB_PORT=5432
      - N8N_METRICS=true

    volumes:
      - n8n_data:/home/node/.n8n
      - ./mount_files:/mount_files

    entrypoint: 
      - "sh"
      - "-c"
      - |
        mkdir -p /home/node/.n8n /home/node/.npm /mount_files;
        exec tini -- /docker-entrypoint.sh

    user: "1000:1000"

  pg-n8n:
    image: postgres:12
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: n8n
    volumes:
    - pg_n8n_data:/var/lib/postgresql/data

volumes:
  pg_n8n_data:
  n8n_data: